### ISSUE TITLE
problems with userpass

### ISSUE THREAD

**Issue by PatrickHeneise** [couchbaselabs/couchbase-server-docker#10]
```
docker attach fdda31a33901
2015/02/07 17:35:56 Checking status returned output: couchbase-server is running
2015/02/07 17:35:56 Couchbase service running
2015/02/07 17:35:56 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:36:06 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:36:16 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:36:26 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:36:36 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:36:46 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:36:56 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:37:06 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:37:16 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:37:26 Got error Failed to GET http://172.31.18.117:8091/pools.  Status code: 401 trying to fetch details.  Assume that the cluster is not up yet, sleeping and will retry
2015/02/07 17:37:36 Unable to fetch cluster details after several attempts
```

I can connect to the web interface, but my userpass ('Administrator:helloworld') doesn't work. I suppose that's also why there's a 401? How to solve that?

**Comment by tleyden** [comment]
When I've run into that, it's usually because I'm trying to start a brand new cluster, even though there is "residue" from the previous cluster in /opt/couchbase/var.

Can you try this workaround? 

* shut everything down
* rm -rf /opt/couchbase/var on all boxes
* try again

**Comment by tleyden** [comment]
Also can you try this? 

* Go to web ui of the couchbase node on port 8091
* Try your password -- does that work?
* Try the [default password](https://github.com/tleyden/couchbase-cluster-go/blob/master/cluster.go#L27-L30) admin/password -- ditto.

**Comment by PatrickHeneise** [comment]
Thanks, deleting the folder worked. Got to the setup screen and set everything up. Is there a way to auto-join new machines into the cluster? With the second server I had to log in and join the node into the cluster, I was hoping distributing userpass in etcd would do that automatically ;)

btw. the node goes down after a few minutes, either 1 or 2, pretty random:

```
fleetctl journal couchbase@1.service
-- Logs begin at Thu 2015-02-05 15:07:14 UTC, end at Sat 2015-02-07 20:35:42 UTC. --
Feb 07 20:33:38 ip-172-31-18-117.ec2.internal bash[7701]: 2015/02/07 20:33:38 Calling FindLiveNode()
Feb 07 20:33:38 ip-172-31-18-117.ec2.internal bash[7701]: 2015/02/07 20:33:38 node: &{Key:/couchbase.com/couchbase-node-state Value: Dir:true Expiration:<nil> TTL:0 Nodes:[] ModifiedIndex:221527 CreatedIndex:221527}
Feb 07 20:33:38 ip-172-31-18-117.ec2.internal bash[7701]: 2015/02/07 20:33:38 len(node.Nodes) == 0, returning
Feb 07 20:33:38 ip-172-31-18-117.ec2.internal bash[7701]: 2015/02/07 20:33:38 liveNodeIp:
Feb 07 20:33:38 ip-172-31-18-117.ec2.internal bash[7701]: 2015/02/07 20:33:38 Sleeping for 100
Feb 07 20:35:18 ip-172-31-18-117.ec2.internal bash[7701]: 2015/02/07 20:35:18 Failed to join cluster after several retries
Feb 07 20:35:18 ip-172-31-18-117.ec2.internal systemd[1]: couchbase@1.service: main process exited, code=exited, status=1/FAILURE
Feb 07 20:35:18 ip-172-31-18-117.ec2.internal systemd[1]: Unit couchbase@1.service entered failed state.
Feb 07 20:35:18 ip-172-31-18-117.ec2.internal systemd[1]: couchbase@1.service failed.
Feb 07 20:35:18 ip-172-31-18-117.ec2.internal docker[8019]: couchbase
```

**Comment by PatrickHeneise** [comment]
The initial join and rebalance was successful, just later it stops working. Not sure what's wrong there.

**Comment by tleyden** [comment]
Do you need couchbase + sync gw, or just couchbase?

Which instructions are you following?

**Comment by tleyden** [comment]
> With the second server I had to log in and join the node into the cluster, I was hoping distributing userpass in etcd would do that automatically ;)

Yeah it should, but maybe it was in a sleep rerty loop.  (Can be tightened)

**Comment by tleyden** [comment]
If you only need couchbase server, try http://tleyden.github.io/blog/2014/11/01/running-couchbase-cluster-under-coreos-on-aws/

**Comment by tleyden** [comment]
> With the second server I had to log in and join the node into the cluster, I was hoping distributing userpass in etcd would do that automatically ;)

I'm working on an improvement for that:  https://github.com/tleyden/couchbase-cluster-go/commit/7a7f4d5e5ebaf61ca41e6fde06941aea1ee89db2

Now it will do a tighter polling loop (every 5s) to see if a rebalance can be done.

Also, what *should* be happening is that it should only run a rebalance once after all nodes are added, rather than doing a rebalance after each node is added.  This will speed things up considerably, but it's a somewhat tricky change.

**Comment by PatrickHeneise** [comment]
I only need Couchbase Server. Going to try again now, thanks a lot! :)

**Comment by PatrickHeneise** [comment]
I'm going to try the latest docker file.

Is there some more information to get this working without the bootstrap scripts? I have my cluster already running and would like to have some more control, not leaving it to Go scripts.
