### ISSUE TITLE
How do you use this?!

### ISSUE THREAD

**Issue by TrollWarlord** [couchbaselabs/couchbase-server-docker#13]
A lot of this repo was changed since I last looked (few days ago). I don't see any fleet files now and the read-me seems to be hard to understand.

How do you actually deploy this on coreos, what's the primary script? (using fleet)

**Comment by tleyden** [comment]
Yeah, it's under development.

The fleet data is currently embedded in the code:

https://github.com/tleyden/couchbase-cluster-go/blob/master/fleet.go#L242-L299

https://github.com/tleyden/couchbase-cluster-go/blob/master/fleet.go#L326-L383

> How do you actually deploy this on coreos, what's the primary script? (using fleet)

The docs are here http://tleyden.github.io/blog/2014/12/15/running-a-sync-gateway-cluster-under-coreos-on-aws/

**Comment by TrollWarlord** [comment]
2015/02/20 23:13:03 Connect to etcd on localhost
2015/02/20 23:13:03 verifyEnoughMachinesAvailable()
2015/02/20 23:13:03 getJsonData error: Get http://localhost:49153/v1-alpha/machines: dial tcp 127.0.0.1:49153: connection refused
2015/02/20 23:13:03 Failed: Get http://localhost:49153/v1-alpha/machines: dial tcp 127.0.0.1:49153: connection refused


When I run it (3 ndoe cluster). 49153 is the fleet port, default it's 4001 though? can I change this?

**Comment by tleyden** [comment]
etcd port: 4001
fleet rest api port: 49153

That error sounds like you aren't using the right cloudformation template.

If your cloudformation template that you are using doesn't have this:

https://github.com/couchbaselabs/couchbase-server-docker/blob/master/aws-cloudformation/couchbase_server.template#L148-L153

then it won't work.  

If you've got an existing cluster, manually creating the `/etc/systemd/system/fleet.socket.d/30-ListenStream.conf` with the contents from above should allow it to contact the fleet api.  (although, you might need to restart the fleet service.. not sure about that one)
