### ISSUE TITLE
Does not handle node restarts (in particular bootstrap node)

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-server-docker#2]
To reproduce:

* Kick off cluster according to the instructions in this [blog post](http://tleyden.github.io/blog/2014/12/15/running-a-sync-gateway-cluster-under-coreos-on-aws/)
* Restart the bootstrap node via `fleetctl stop couchbase_bootstrap_node.service && fleetctl start couchbase_bootstrap_node.service`

You will end up with a "split cluster" as shown here:

* http://cl.ly/image/1S2F2k0H0c17?_ga=1.48706405.257213425.1401744125
* http://cl.ly/image/3c073k2r251k?_ga=1.73874641.257213425.1401744125

The problem is that when the bootstrap node is started, it starts a *new cluster* rather than joining the existing cluster, because the couchbase-start script is invoked with the -bootstrap flag and it runs [these commands](https://github.com/couchbaselabs/couchbase-server-docker/blob/master/3.0.1/scripts/couchbase-start#L31-L65). 

For non-bootstrap nodes, when the node comes back up, it will require a rebalance before joining the cluster, which is not currently automated.

The issue is exacerbated by the fact that [CoreOS will automatically restart itself when there are new security updates](https://coreos.com/using-coreos/updates/).

**Comment by andrewwebber** [comment]
I don't know if its helpful but i worked around this issue by deleting as quickly as possible the bootstrap node.

I used initially [dustin's docker container](https://gist.github.com/dustin/6605182) and created the following systemd unit files.

Basically i have each cluster node overridewrite a single etcd path with a TTL. In addition the persistence option for the docker container is quite useful because of restarting the container we can kill its, remove it and start a fresh one with that mount directory. 

Bootstrap-couchbase.service
```yaml
[Unit]
Description=couchbase Service
After=docker.service
After=setup-network-environment.service
Requires=docker.service

[Service]
TimeoutStartSec=10m
ExecStartPre=-/usr/bin/mkdir -p /home/core/data/couchbase
ExecStartPre=-/usr/bin/docker kill couchbase
ExecStartPre=-/usr/bin/docker rm -f couchbase
ExecStartPre=/usr/bin/docker pull dustin/couchbase
ExecStart=/usr/bin/docker run --name couchbase --net host -v /home/core/data/couchbase:/opt/couchbase/var dustin/couchbase
ExecStop=/usr/bin/docker stop -t 2 couchbase
Restart=always
RestartSec=20
```

Bootstrap-couchbase-announce.service
```yaml
[Unit]
Description=Announce Couchbase
BindsTo=couchbase.service
After=couchbase.service

[Service]
EnvironmentFile=/etc/network-environment
ExecStart=/bin/sh -c "while true; do etcdctl --peers 172.20.11.54:4001 --no-sync set /services/couchbase ${DEFAULT_IPV4} --ttl 60;sleep 45;done"
Restart=always
RestartSec=20
```

Then i have the following scale out unit files that can be globally deployed

Scaleout-couchbase.service
```yaml
[Unit]
Description=couchbase Service
After=docker.service
After=setup-network-environment.service
Requires=docker.service

[Service]
TimeoutStartSec=10m
ExecStartPre=-/usr/bin/mkdir -p /home/core/data/couchbase
ExecStartPre=-/usr/bin/docker kill couchbase
ExecStartPre=-/usr/bin/docker rm -f couchbase
ExecStartPre=/usr/bin/docker pull dustin/couchbase
ExecStart=/usr/bin/sh -c "/usr/bin/docker run --name couchbase --net host -v /home/core/data/couchbase:/opt/couchbase/var -e ALPHA_PORT_7081_TCP_ADDR=$(etcdctl --peers 172.20.11.54:4001 --no-sync get /services/couchbase) dustin/couchbase"
ExecStop=/usr/bin/docker stop -t 2 couchbase
Restart=always
RestartSec=10
```

Scaleout-couchbase-announce.service
```yaml
[Unit]
Description=Announce Couchbase
BindsTo=couchbase.service
After=couchbase.service

[Service]
Restart=always
RestartSec=10
EnvironmentFile=/etc/network-environment
ExecStart=/bin/sh -c "while true; do etcdctl --peers 172.20.11.54:4001 --no-sync set /services/couchbase ${DEFAULT_IPV4} --ttl 60;sleep 45;done"
```

**Comment by tleyden** [comment]
Hey @andrewwebber, thanks for posting this!  

> I used initially dustin's docker container and created the following systemd unit files.

Any reason you need to use Dustin's docker container here rather than https://registry.hub.docker.com/u/tleyden5iwx/couchbase-server-2.2.0 or https://registry.hub.docker.com/u/tleyden5iwx/couchbase-server-3.0.1?  The reason I mention it is that Dustin is no longer with couchbase, nor is he using Docker any more that I know of.  Let me know what functionality you need from the dockerfile/image, and maybe we can merge that into the ones I've been working on.  

> Basically i have each cluster node overridewrite a single etcd path with a TTL

Ok so the last node that startuped up will have its ip recorded in etcd?  And that way, any node who wants to join the cluster will just use that ip?

> In addition the persistence option for the docker container is quite useful because of restarting the container we can kill its, remove it and start a fresh one with that mount directory.

I haven't heard about that option -- can you explain it and/or point to some docs?  Also what problem are you solving by using this option?  (losing the config files between service restarts?)

**Comment by tleyden** [comment]
From Patrick Varley from the Couchbase support engineering team:

To answer your questions from Hipchat.

Q1: When you say "recover", does that mean "rebalance"?
Q2: What is the difference between shutting down a cb server node after first doing a graceful failover vs just shutting it down?  what does the failover actually do?  (as you can see I'm still wrapping my head around this couchbase beast)

Let me explain when you should use failover and then I will move on to what happens under the covers. Failover is a pretty brutal process that should only be used when you need to remove a node out of the cluster ASAP without using the normal rebalance process.
For instance if there was a hardware/OS fault on one of the nodes. When failover is triggered (automatically or manually) the cluster will promote all replica vbuckets for the active vbuckets that were on the node that being failed over. Any operations on the failed over node that were accepted but not replica will be lost, this referred to as inflight operations. One thing to note is that when you failover a node it is still part of the cluster it is just not serving any data. After a failover you can decide whether to add the node back in or to remove it from the cluster, this is done via a rebalance that will rebuild the replica vbucket set. In general you should only failover when there are enough replicas otherwise data will be lost, in caching situation this might be acceptable. 

In 3.0 we introduce a new type of failover called "Graceful Failover”. This is not as fast as the normal failover i.e it could take a few seconds/minutes but no inflight operations will be lost. The ideal behind Graceful failover is when you have a large data set that is not resident in memory and you are required to do some maintenance on that node, like OS security updates. Before 3.0 you would do a swap rebalance but in these situations that could  take hours maybe even a day. With graceful failover you can remove the node from the cluster, do your maintenance and then when you add the node back you have the ability to do a delta node recovery. This will only transfer the differences in data while the nodes was failed over. One thing to be aware of during the maintenance period some of the active vbucket will not have replicas and as a result if something bad was to go wrong on the cluster you could lose data.

During a normal add and remove rebalance the cluster always ensure there is a full set of replica vbucket.

To answer your last point about “just shutting down”, if auto fail is enabled (by default it is not) the cluster will fail over that node after the failover time period the default is 120 seconds. If the node is never failed over the data (vbucket) that lives on that node will not be accessible. 

Every thing I mention here assumes that replicas are enabled. :)

**Comment by andrewwebber** [comment]
> Any reason you need to use Dustin's docker container...

I have historically bring using his container as it was the first docker container for couchbase. I have now moved on to other containers.

> Ok so the last node that startuped up will have its ip recorded in etcd? And that way, any node who wants to join the cluster will just use that ip?

This is correct. For me concern became obvious when trying to deploy a systemd file with fleet. The systemd file needs to be generic enough to handle random server restarts. The way I got round this was to
1. have an initial setup of a master node. 
2. Then deploy systemd files for the 'rebalance' nodes.
3. Finally remove the master and replace it with a 'rebalance' systemd unit (if you get what i mean)

Again my concern initially arose as i have auto updates on coresos that just brutally restart the servers when updates are detected. This means that any know could be restarted at any time and on boot up should rebalance with the cluster. 

Having each of the 'rebalance' nodes overwrite a single etcd entry allows me to rebalance to any node on reboot.

> I haven't heard about that option -- can you explain it and/or point to some docs?

If you look at the original container from [dustin](https://registry.hub.docker.com/u/dustin/couchbase/) if exposes the persistence data as a docker volume.
``` bash
sudo docker run -d -v /home/core/data/couchbase:/opt/couchbase/var
```

This initially provided my with peace of mind knowing that I always knew where my data was, if I didn't perform a backup. However now i use the couchbase-cli to perform backups and this may not be such an important issue.

I hope that helps.

kind regards,

**Comment by tleyden** [comment]
> I have historically bring using his container as it was the first docker container for couchbase. I have now moved on to other containers.

Do you have any Dockerfiles you can share?  The reason I ask is because I'm pushing for an "official" Docker image, which would have an associated Dockefile.  Anything you could share would be useful.

>  For me concern became obvious when trying to deploy a systemd file with fleet. The systemd file needs to be generic enough to handle random server restarts. The way I got round this was to .. [snip]

Thanks, that is useful, I may end up adopting that approach.  I'm still a bit confused though -- when are you doing the actual rebalance?  I don't see any rebalance commands in your systemd files, so does that mean you are doing it from a shell script or manually via the web UI?

> If you look at the original container from dustin if exposes the persistence data as a docker volume.

Oh, gotcha.  Yes I'm also using docker volumes, as can be seen in this [systemd file](https://github.com/couchbaselabs/couchbase-server-docker/blob/master/3.0.1/fleet/couchbase_node.service.template#L10).  However, I see value in the approach you mentioned in that you are also capturing the logs or anything else that appears under `/opt/couchbase/var`, whereas I'm explicitly only persisting the data and index directories, due to these [calls to the couchbase-cli](https://github.com/couchbaselabs/couchbase-server-docker/blob/master/templates/couchbase-start.template#L45-L50).

**Comment by tleyden** [comment]
I just had a brainstorming session with @jamesmauss, and here's what we came up with:

All nodes would be equal rather than having a special "bootstrap node".  

When a node comes up:

* It will try to be the cluster-first-node (see notes below)
     * If succeeds:
          * `couchbase-cli cluster-init &&  couchbase-cli bucket-create`
     * Else: (there is already a cluster)
          * Find list of machines in cluster from etcd
          * For each machine, get ip and see /node-state/<ip> key exists
          * As soon as an existing node is found, join it via `couchbase-cli server-add`
          * If none are found that can be joined, abort with an error

## Becoming the first cluster node

Use the etcd ADD operation `client.write('/cluster-first-node', '<our ip address>', prevExist=False)` -- Only the first one to do this will succeed.

## Maintaining /node-state/<node ip> entries

Each node service will have a [simple sidekick](https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/) that publishes its ip into ` /node-state/<node ip>` with a TTL.  It will use the same strategy that current [bootstrap sidekick](https://github.com/couchbaselabs/couchbase-server-docker/blob/master/2.2.0/fleet/couchbase_bootstrap_node_announce.service#L8) uses.

@andrewwebber - this should bring things closer to your approach, but hopefully in a cleaner way.  Any thoughts?

**Comment by andrewwebber** [comment]
@tleyden This would be awesome. It sounds like the right approach and direction. I'll have a play around next week see if I can refactor my systemd unit files. Great idea

**Comment by tleyden** [comment]
@andrewwebber glad to hear.  The [couchbase-start](https://github.com/couchbaselabs/couchbase-server-docker/blob/master/templates/couchbase-start.template) script will need a lot of work as well, and I started to rewrite it in python, then got frustrated with python dependency hell and switched to Go.  As I've been digging into it, I'm discovering a lot more power in etcd, such as the ability to [add a key only if it didn't already exist](https://godoc.org/github.com/coreos/go-etcd/etcd#Client.Create).

Here's the script in progress:

https://github.com/couchbaselabs/couchbase-server-docker/blob/master/scripts/couchbase-start/main.go#L23-L49

**Comment by tleyden** [comment]
@jamesmauss ok it's all coded up on the feature/experimental branch, and so far it's working like a charm.  I can bounce any node and it rejoins once it comes back up.

One thing baffled me though:  I could not figure out how to do the equivalent of:

```
couchbase-cli rebalance -c 192.168.0.1:8091 \
    --server-add=192.168.0.2:8091 \
    --server-add-username=Administrator \
    --server-add-password=password
```

via the REST api.  

I was looking at [these docs](http://docs.couchbase.com/couchbase-manual-2.5/cb-rest-api/#rebalancing-nodes) and was confused by this syntax:

```
-d 'ejectedNodes=&knownNodes=ns_1%40192.168.0.77%2Cns_1%40192.168.0.56'
```

When I tried to list the nodes as described [here](http://docs.couchbase.com/couchbase-manual-2.5/cb-rest-api/#couchbase-admin-restapi-node-management) I didn't see any descriptors of the nodes that started with **ns_1**.  

In the meantime, I'm just using the cli for that particular operation: [code to kick off rebalance](https://github.com/couchbaselabs/couchbase-server-docker/blob/feature/experimental/scripts/couchbase-start/main.go#L413-L469)

**Comment by tleyden** [comment]
Fixed and deployed, [blog post](http://tleyden.github.io/blog/2014/12/15/running-a-sync-gateway-cluster-under-coreos-on-aws/) updated.

**Comment by tleyden** [comment]
@andrewwebber hoping to get your feedback on this update.

Btw, if you startup a new cluster and want to migrate the data between sync gateways, check out [sg-replicate](https://github.com/couchbaselabs/sg-replicate)
