### ISSUE TITLE
Remove couchbase node from cluster before restart

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-server-docker#3]
Currently CoreOS will auto-update and auto-reboot nodes when new security patches are available.  

Couchbase Server nodes should be first removed from the cluster and the cluster should be rebalanced before the OS reboot occurs.  After the machine is back up, the node should be re-added to the cluster.

Currently, this doesn't seem to be happening.  I have started a [thread](https://groups.google.com/forum/#!topic/coreos-user/65_emqEKlr8) on the CoreOS mailing list asking how to do this.  

I'm not sure what the negative side effects are of not doing this.

**Comment by tleyden** [comment]
## 3.x

* [Graceful failover](http://docs.couchbase.com/admin/admin/Concepts/graceful-failover.html) on node shutdown
* [Delta node recovery](http://docs.couchbase.com/admin/admin/Concepts/delta-node-recovery.html)

## 2.x

* Failover
* Recovery (re-add + rebalance)

**Comment by tleyden** [comment]
> I'm not sure what the negative side effects are of not doing this.

If a node in a 3 node cluster goes down without a failover happening, then 1/3'd of the keyspace will be unavailable while it's down.

**Comment by tleyden** [comment]
Worse -- if there is 5 node cluster with Couchbase Server running on 3 nodes, and a node restarts, the situation is even worse because the new node comes up on a different ip, and the cluster is waiting for the old node to rejoin.

**Comment by tleyden** [comment]
This has been fixed on the support/0.8 branch, and the blog post updated.

Once the cluster is up, you can test by ssh'ing into any node and running "sudo reboot", which triggers:

* Remove that node from cb cluster
* Trigger a rebalance
* Wait for rebalance
* Machine shutdown
* Machine startup
* Re-add that node into cluster
* Rebalance

**Comment by tleyden** [comment]
## Before reboot

![screen shot 2015-02-25 at 7 33 35 am](https://cloud.githubusercontent.com/assets/296876/6373717/521e0f3a-bcc1-11e4-909c-6383fd023b26.png)

## Trigger reboot

![screen shot 2015-02-25 at 7 33 48 am](https://cloud.githubusercontent.com/assets/296876/6373733/639071f4-bcc1-11e4-9360-b31859b97fe9.png)

## Remove and rebalance automatically triggered

Due to the ExecStop section in the fleet unit, the node is removed from the couchbase cluster and a rebalance is triggered.

![screen shot 2015-02-25 at 7 33 54 am](https://cloud.githubusercontent.com/assets/296876/6373745/83529346-bcc1-11e4-802c-023d9e4cac7e.png)

## Rebooted machine no longer in couchbase cluster

![screen shot 2015-02-25 at 7 44 08 am](https://cloud.githubusercontent.com/assets/296876/6373871/35e3e19a-bcc2-11e4-9c1b-45da89d658b4.png)

## Rebooted machine no longer in coreos cluster

![screen shot 2015-02-25 at 7 44 20 am](https://cloud.githubusercontent.com/assets/296876/6373879/3cb01232-bcc2-11e4-84fe-e16d8d210d5a.png)

## Post machine reboot, auto-rejoins couchbase cluster and triggers rebalance

![screen shot 2015-02-25 at 7 46 27 am](https://cloud.githubusercontent.com/assets/296876/6373920/7ec039fe-bcc2-11e4-9b4b-5e4f18232628.png)

**Comment by rollsappletree** [comment]
Guys I have a problem with this approach. 
when i shut down a node a remove_from_cluster_thus_rebalance is triggered, but the node is shut down BEFORE it finished, leaving the cluster in an inconsistent state.

do you have any advice at how to avoid that? maybe a sleep?
