### ISSUE TITLE
Cluster wont come up

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/couchbase-server-docker#4]
Only the first couchbase server container is able to connect to etcd, the rest get errors.

**Comment by tleyden** [comment]
I think the root cause is https://github.com/coreos/go-etcd/issues/179

**Comment by tleyden** [comment]
@PaulCapestany I think the cleanest workaround is to pin the dependency on go-etcd to a previous known working version.  (using godep or something similar)

**Comment by PaulCapestany** [comment]
@tleyden, yeah, I was starting to look into how one does a "rollback" with CoreOS, or sets a particular version/commit of etcd to use. Still researching though.

**Comment by tleyden** [comment]
A rollback won't help, because the bug is in the go-etcd client, which is directly included as a dependency [here](https://github.com/tleyden/couchbase-cluster-go/blob/master/cluster.go#L18).  When the container starts up, it uses that code to talk to the etcd server and get the list of couchbase server nodes.

**Comment by tleyden** [comment]
@PaulCapestany a "roll forward" would probably work though, since it was mentioned in https://github.com/coreos/go-etcd/issues/179 that the master branch of go-etcd works against the new 2.0 version of etcd.  I haven't checked which version/channel of CoreOS has etcd 2.0 though.

Btw I've got a workaround in place which pins the go-etcd client dependency to an older version.  I'm just verifying it right now.

**Comment by tleyden** [comment]
Worked around the problem in https://github.com/couchbaselabs/couchbase-server-docker/commit/a7527bc458279a1462b3443c21d3d5b57e2e4b3c.  It just uses an older version of go-etcd for now.

I retested using the instructions in [Running a Sync Gateway Cluster Under CoreOS on AWS](http://tleyden.github.io/blog/2014/12/15/running-a-sync-gateway-cluster-under-coreos-on-aws/) on both Couchbase server 2.2.0 and 3.0.1.

**Comment by PaulCapestany** [comment]
@tleyden your workaround seems to be working for me — thanks!
