### ISSUE TITLE
Use encrypted EBS for data?

### ISSUE THREAD

**Issue by PatrickHeneise** [couchbaselabs/couchbase-server-docker#8]
Hi there,

thanks for putting this together. I'm about to launch it into a cluster. I would like to know if it's possible to mount an encrypted EBS volume to store the data? Does that work with

```
[Mount]
        What=/dev/xvdf
        Where=/var/lib/docker
```

in the unit file?

**Comment by tleyden** [comment]
Hi @PatrickHeneise glad to see you are interested in this project.  I haven't tried using ebs encrypted volumes, but will try to help.

Do you mean this unit file?  https://github.com/couchbaselabs/couchbase-server-docker/blob/master/templates/fleet/couchbase_node%40.service.template

Also can you point me to the documentation where you got that example above?

You might also consider asking on the [CoreOS user](https://groups.google.com/forum/#!forum/coreos-user) google group.

**Comment by PatrickHeneise** [comment]
Yes, put the question there as well. I did mount the drive manually on both servers and point it to /opt/couchbase/var/lib/couchbase/data, will see how to automate that later in fleet.
